### ISSUE TITLE
Refactor smart-contracts

### ISSUE THREAD

**Issue by daseinsucks** [daseinsucks/MultisigLegacy#3]
Smart-contracts are really ugly. Logic & style should be edited.

**Comment by JackBekket** [comment]
Front-end is just `shit-n-stick's`

I mean it's impossible to even **build** this thing

It some how work with current ABI, despite we change code *inside* of some functions, but I've managed to only *run* this thing in dev mode, *without* rebuilding

If you try to make significantly change contracts you have to rebuild new ABI and in this case Front-end dapp become santient, relize it's ugliness and commit suicide from a shotgun irreversibly

**Comment by JackBekket** [comment]
However *there is* actually one thing we desperetly need

**Comment by JackBekket** [comment]
I need to get interfaceID from multisigs contracts, so I can be sure that user can't attach scum to the group chat in telegram

Can u please add interfaceID to Multisig contract?

**Comment by JackBekket** [comment]
Also I would like to ask if it's possible to generate go-lang artifacts? I don't need it now, but they will be required for future

**Comment by daseinsucks** [comment]
Done... Almost...
